image:
- Visual Studio 2015
- Visual Studio 2017

version: '1.0.0.{build}'
platform: 
  - Any CPU

configuration:
  - Debug
  - Release

before_build:
- nuget restore Gneuton.sln

build:
  project: Gneuton.sln
  verbosity: minimal

test:
  assemblies:
    - 'Build\Output\*Tests.dll'

    
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-{branch}"

deploy: off